# Base configs
baseurl: "https://ashxcode.github.io/photography/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Photography by Ashley Betances"
subtitle: "An on going project in film photography"
author: "Ashley Betances"

footer: Ashley Betances
 name: "Hey there, my name is Ashley"
 bio: "I am a film photographer."
social_urls:
  instagram: "https://www.instagram.com/ashvegan"
 
