# Base configs
baseurl: "https://ashxcode.github.io/photography/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Ashley Betances"
subtitle: "film photography"
author: "Ram Patra"
header:
 title: "Photography"
 subtitle: "by Ashley Betances"
footer:
 name: "Hey there, my name is Ashley"
 bio: "I am a film photographer."
social_urls:
  instagram: "https://www.instagram.com/ashvegan"
 
